export const RESET = 'RESET'
export const CLEAR_LOGIN = 'CLEAR_LOGIN'
export const LOGIN = 'LOGIN'
export const RELOAD_LOGIN = 'RELOAD_LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const SET_SIGNUP_STATUS = 'SET_SIGNUP_STATUS'
