export const SET_USER_DOCUMENTS = 'SET_USER_DOCUMENTS'
export const SET_CURRENT_USER_DOCUMENTS = 'SET_CURRENT_USER_DOCUMENTS'
export const SET_UPLOAD_STATUS = 'SET_UPLOAD_STATUS'
export const SET_CURRENT_DOCUMENT = 'SET_CURRENT_DOCUMENT'
